"""Add is_komiteeleitung to User model

Revision ID: 0aa1c633f3ea
Revises: d1704d67c7dc
Create Date: 2026-04-16 09:52:04.851288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa1c633f3ea'
down_revision = 'd1704d67c7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_komiteeleitung', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_komiteeleitung')

    # ### end Alembic commands ###
