"""Add Treffen model and extend Wortmeldung with kategorie, status, treffen_id

Revision ID: d1704d67c7dc
Revises: 
Create Date: 2026-04-02 16:01:01.592539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1704d67c7dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wortmeldungen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategorie', sa.String(length=50), server_default='vorfall', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='offen', nullable=False))
        batch_op.add_column(sa.Column('treffen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_wortmeldungen_treffen_id', 'treffen', ['treffen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wortmeldungen', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wortmeldungen_treffen_id', type_='foreignkey')
        batch_op.drop_column('treffen_id')
        batch_op.drop_column('status')
        batch_op.drop_column('kategorie')

    # ### end Alembic commands ###
